env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash
    
task:
    name: rom
    timeout_in: 4h
    container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32g
    
    sync_script:
      - bash sync
    build_script:
      - bash build
